<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="Unity.AI.Toolkit.Accounts.Components.xsd" namespace="Unity.AI.Toolkit.Accounts.Components" />
  <xs:import schemaLocation="UnityEngine.UIElements.xsd" namespace="UnityEngine.UIElements" />
  <xs:import schemaLocation="Unity.AI.Sound.Components.xsd" namespace="Unity.AI.Sound.Components" />
  <xs:import schemaLocation="Unity.AI.Pbr.Components.xsd" namespace="Unity.AI.Pbr.Components" />
  <xs:import schemaLocation="Unity.AI.ModelSelector.Components.xsd" namespace="Unity.AI.ModelSelector.Components" />
  <xs:import schemaLocation="Unity.AI.Mesh.Components.xsd" namespace="Unity.AI.Mesh.Components" />
  <xs:import schemaLocation="Unity.AI.Image.Components.xsd" namespace="Unity.AI.Image.Components" />
  <xs:import schemaLocation="Unity.AI.Image.Panel.xsd" namespace="Unity.AI.Image.Panel" />
  <xs:import schemaLocation="Unity.AI.Generators.UI.xsd" namespace="Unity.AI.Generators.UI" />
  <xs:import schemaLocation="Unity.AI.Assistant.UI.Editor.Scripts.Components.xsd" namespace="Unity.AI.Assistant.UI.Editor.Scripts.Components" />
  <xs:import schemaLocation="UnityEngine.xsd" namespace="UnityEngine" />
  <xs:import schemaLocation="Unity.AI.Assistant.UI.Editor.Scripts.Components.PromptPopup.xsd" namespace="Unity.AI.Assistant.UI.Editor.Scripts.Components.PromptPopup" />
  <xs:import schemaLocation="Unity.AI.Assistant.UI.Editor.Scripts.xsd" namespace="Unity.AI.Assistant.UI.Editor.Scripts" />
  <xs:import schemaLocation="Unity.AI.Assistant.Editor.SessionBanner.xsd" namespace="Unity.AI.Assistant.Editor.SessionBanner" />
  <xs:import schemaLocation="Unity.AI.Animate.Components.xsd" namespace="Unity.AI.Animate.Components" />
  <xs:import schemaLocation="UnityEditor.U2D.Tooling.Analyzer.UIElement.xsd" namespace="UnityEditor.U2D.Tooling.Analyzer.UIElement" />
  <xs:import schemaLocation="UnityEditor.U2D.Tooling.Analyzer.xsd" namespace="UnityEditor.U2D.Tooling.Analyzer" />
  <xs:import schemaLocation="UnityEditor.U2D.Tooling.Analyzer.UIElement.OKCancel.xsd" namespace="UnityEditor.U2D.Tooling.Analyzer.UIElement.OKCancel" />
  <xs:import schemaLocation="UnityEditor.Tilemaps.xsd" namespace="UnityEditor.Tilemaps" />
  <xs:import schemaLocation="UnityEditor.UIElements.xsd" namespace="UnityEditor.UIElements" />
  <xs:import schemaLocation="UnityEditor.Tilemaps.External.xsd" namespace="UnityEditor.Tilemaps.External" />
  <xs:import schemaLocation="UnityEditor.U2D.Sprites.SpriteEditorTool.xsd" namespace="UnityEditor.U2D.Sprites.SpriteEditorTool" />
  <xs:import schemaLocation="UnityEditor.U2D.Animation.xsd" namespace="UnityEditor.U2D.Animation" />
  <xs:import schemaLocation="UnityEditor.U2D.Animation.SpriteLibraryEditor.xsd" namespace="UnityEditor.U2D.Animation.SpriteLibraryEditor" />
  <xs:import schemaLocation="UnityEditor.U2D.Layout.xsd" namespace="UnityEditor.U2D.Layout" />
  <xs:import schemaLocation="UnityEditor.U2D.Animation.Upgrading.xsd" namespace="UnityEditor.U2D.Animation.Upgrading" />
  <xs:import schemaLocation="Unity.UIToolkit.Editor.xsd" namespace="Unity.UIToolkit.Editor" />
  <xs:import schemaLocation="UnityEditor.UIElements.Debugger.xsd" namespace="UnityEditor.UIElements.Debugger" />
  <xs:import schemaLocation="Unity.UI.Builder.xsd" namespace="Unity.UI.Builder" />
  <xs:import schemaLocation="UnityEditor.Search.xsd" namespace="UnityEditor.Search" />
  <xs:import schemaLocation="Unity.Multiplayer.PlayMode.Editor.xsd" namespace="Unity.Multiplayer.PlayMode.Editor" />
  <xs:import schemaLocation="UnityEditor.Experimental.GraphView.xsd" namespace="UnityEditor.Experimental.GraphView" />
  <xs:import schemaLocation="Unity.GraphToolkit.ItemLibrary.Editor.xsd" namespace="Unity.GraphToolkit.ItemLibrary.Editor" />
  <xs:import schemaLocation="Unity.GraphToolkit.Editor.xsd" namespace="Unity.GraphToolkit.Editor" />
  <xs:import schemaLocation="UnityEditor.Toolbars.xsd" namespace="UnityEditor.Toolbars" />
  <xs:import schemaLocation="UnityEditor.Animations.AnimationWindow.Widgets.xsd" namespace="UnityEditor.Animations.AnimationWindow.Widgets" />
  <xs:import schemaLocation="UnityEditor.PackageManager.UI.Internal.xsd" namespace="UnityEditor.PackageManager.UI.Internal" />
  <xs:import schemaLocation="Unity.Profiling.Editor.UI.xsd" namespace="Unity.Profiling.Editor.UI" />
  <xs:import schemaLocation="Unity.Profiling.Editor.xsd" namespace="Unity.Profiling.Editor" />
  <xs:import schemaLocation="UnityEditor.Audio.UIElements.xsd" namespace="UnityEditor.Audio.UIElements" />
  <xs:import schemaLocation="UnityEditor.UIElements.ProjectSettings.xsd" namespace="UnityEditor.UIElements.ProjectSettings" />
  <xs:import schemaLocation="UnityEditor.Animations.AnimationWindow.TimelineFoundation.xsd" namespace="UnityEditor.Animations.AnimationWindow.TimelineFoundation" />
  <xs:import schemaLocation="UnityEditor.Inspector.GraphicsSettingsInspectors.xsd" namespace="UnityEditor.Inspector.GraphicsSettingsInspectors" />
  <xs:import schemaLocation="UnityEditor.Overlays.xsd" namespace="UnityEditor.Overlays" />
  <xs:import schemaLocation="UnityEditor.ShortcutManagement.xsd" namespace="UnityEditor.ShortcutManagement" />
  <xs:import schemaLocation="UnityEditor.Inspector.xsd" namespace="UnityEditor.Inspector" />
  <xs:import schemaLocation="UnityEditor.xsd" namespace="UnityEditor" />
  <xs:import schemaLocation="UnityEditor.Accessibility.xsd" namespace="UnityEditor.Accessibility" />
  <xs:import schemaLocation="UnityEngine.Accessibility.xsd" namespace="UnityEngine.Accessibility" />
</xs:schema>